{{- if and .Values.build.enabled (eq .Values.build.output.kind "ImageStreamTag") -}}

{{- if .Values.build.s2i.buildApplicationImage -}}
{{- include "wildfly-common.imagestream" (list . "wildfly.metadata.labels") }}
{{- end -}}

{{- if eq .Values.build.mode "s2i" }}
---
{{ include "wildfly-common.imagestream-s2i-build-artifacts" (list . "wildfly.metadata.labels") }}
{{- end -}}
{{- end -}}